version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  btc-ltp-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDRESS=redis:6379

  goswagger:
    image: quay.io/goswagger/swagger
    command: generate server --exclude-main --exclude-spec -t internal/ -f swagger.yaml --name rest-server
    user: "${UID}:${GID}"
    environment:
      - GOPATH=${GOPATH}:/go
    volumes:
      - "${HOME}:${HOME}"
    working_dir: "${PWD}"