version: '3.8'

services:
  btc-ltp-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MAX_CONCURRENCY=5

  goswagger:
    image: quay.io/goswagger/swagger
    command: generate server --exclude-main --exclude-spec -t internal/ -f swagger.yaml --name rest-server
    user: "${UID}:${GID}"
    environment:
      - GOPATH=${GOPATH}:/go
    volumes:
      - "${HOME}:${HOME}"
    working_dir: "${PWD}"