// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetLtpHandlerFunc turns a function with the right signature into a get ltp handler
type GetLtpHandlerFunc func(GetLtpParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLtpHandlerFunc) Handle(params GetLtpParams) middleware.Responder {
	return fn(params)
}

// GetLtpHandler interface for that can handle valid get ltp params
type GetLtpHandler interface {
	Handle(GetLtpParams) middleware.Responder
}

// NewGetLtp creates a new http.Handler for the get ltp operation
func NewGetLtp(ctx *middleware.Context, handler GetLtpHandler) *GetLtp {
	return &GetLtp{Context: ctx, Handler: handler}
}

/*
	GetLtp swagger:route GET /ltp getLtp

Get Last Traded Price (LTP) for currency pairs
*/
type GetLtp struct {
	Context *middleware.Context
	Handler GetLtpHandler
}

func (o *GetLtp) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetLtpParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
