// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"test-assigment-ltp/internal/models"
)

// GetLtpOKCode is the HTTP code returned for type GetLtpOK
const GetLtpOKCode int = 200

/*
GetLtpOK Successful response

swagger:response getLtpOK
*/
type GetLtpOK struct {

	/*
	  In: Body
	*/
	Payload *models.LastTradedPriceResponse `json:"body,omitempty"`
}

// NewGetLtpOK creates GetLtpOK with default headers values
func NewGetLtpOK() *GetLtpOK {

	return &GetLtpOK{}
}

// WithPayload adds the payload to the get ltp o k response
func (o *GetLtpOK) WithPayload(payload *models.LastTradedPriceResponse) *GetLtpOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ltp o k response
func (o *GetLtpOK) SetPayload(payload *models.LastTradedPriceResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLtpOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetLtpBadRequestCode is the HTTP code returned for type GetLtpBadRequest
const GetLtpBadRequestCode int = 400

/*
GetLtpBadRequest Bad request (missing 'pair' parameter)

swagger:response getLtpBadRequest
*/
type GetLtpBadRequest struct {
}

// NewGetLtpBadRequest creates GetLtpBadRequest with default headers values
func NewGetLtpBadRequest() *GetLtpBadRequest {

	return &GetLtpBadRequest{}
}

// WriteResponse to the client
func (o *GetLtpBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetLtpInternalServerErrorCode is the HTTP code returned for type GetLtpInternalServerError
const GetLtpInternalServerErrorCode int = 500

/*
GetLtpInternalServerError Internal server error

swagger:response getLtpInternalServerError
*/
type GetLtpInternalServerError struct {
}

// NewGetLtpInternalServerError creates GetLtpInternalServerError with default headers values
func NewGetLtpInternalServerError() *GetLtpInternalServerError {

	return &GetLtpInternalServerError{}
}

// WriteResponse to the client
func (o *GetLtpInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
