// Code generated by go-swagger; DO NOT EDIT.

// Package restapi LTP Service
//
//	API for retrieving the Last Traded Price (LTP) for various currency pairs.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
